FROM debian:bullseye

RUN apt update; \
    apt upgrade && apt install -y nginx openssl

RUN apt install -y php php-fpm 

RUN mkdir -p /var/run/nginx

RUN mkdir -p /etc/nginx/ssl

RUN mkdir -p /run/php/
RUN chmod 733 /run/php/
RUN chown www-data:www-data /run/php/

# Generate a self-signed SSL certificate and key
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -subj "/C=MA/ST=Khouribga/L=Khouribga/O=1337/CN=aaammari.42.fr/UID=aaammari" \
    -keyout /etc/nginx/ssl/nginx.key \
    -out /etc/nginx/ssl/nginx.crt

COPY ./conf/default.conf /etc/nginx/conf.d/default.conf

COPY ./html /var/www/html

COPY ./php/test.php /var/www/html/test.php

COPY ./tools/script.sh /script.sh

EXPOSE 443

CMD ["/bin/bash", "/script.sh"]
